version: "3.7"

services:
  bitcoind:
    container_name: "bitcoind"
    image: bitcoin-signet
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/.bitcoin:/root/.bitcoin
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: $BLOCKPRODUCTIONDELAY
      NBITS: $NBITS
      RPCPASSWORD: $RPCPASSWORD
      PRIVKEY: $PRIVKEY
      SIGNETCHALLENGE: $SIGNETCHALLENGE
      EXTERNAL_IP: $EXTERNAL_IP
    ports:
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "38332:38332"
      - "38333:38333"
      - "38334:38334"
  electrs:
    container_name: "electrs"
    image: getumbrel/electrs:v0.9.10@sha256:7b64bf93f2137fcd040fc512a302abda17dd1b4cad8181a14fa34c15361f1334
    restart: always
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "signet"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:38332"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:38333"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50001"
      ELECTRS_SERVER_BANNER: "Mutinynet Electrs"
      ELECTRS_DB_DIR: "/data/db"
    volumes:
      - "~/volumes/.bitcoin:/root/.bitcoin:ro"
      - "~/volumes/electrs:/data"
    ports:
      - "50001:50001"
      - "50002:50002"
  faucet:
    container_name: "faucet"
    build:
      context: ./mutinynet-faucet
      args:
        VITE_HOST: "bitcoind"
        VITE_PORT: "38332"
        VITE_USER: "bitcoin"
        VITE_PASS: $RPCPASSWORD
        VITE_NETWORK: "regtest" # wrong intentionally because of bug in a library
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/faucet:/root/.faucet
    ports:
      - "3000:3000"
  web:
    container_name: "mempool_frontend"
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8080:8080"
  api:
    container_name: "mempool_backend"
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "bitcoind"
      CORE_RPC_PORT: "38332"
      CORE_RPC_USERNAME: "bitcoin"
      CORE_RPC_PASSWORD: $RPCPASSWORD
      CORE_RPC_TIMEOUT: "60000"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    ports:
      - "8889:8889"
    volumes:
      - ~/volumes/mempool:/backend/cache
  db:
    container_name: "mempool_db"
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/mysql/data:/var/lib/mysql
